name: "Multi event pipeline / workflow" # Name of the pipeline
on:
    push: # Event: Whenever a push is made to the repository on the master branch
        branches:
            - master
            - test

jobs:
    on-push: #Job name
        runs-on: ubuntu-latest
        steps: # steps to be executed in the job
            - name: "Running on master push" # Step 1
              run: echo "Running on master push"


